### ISSUE TITLE
[SOLVED] Task for Stylus

### ISSUE THREAD

**Issue by ednilsonamaral** [jackfranklin/gulp-load-plugins#112]
If I use Stylus with Jeet, in gulpfie.js, usually I declare:  

```css  
.pipe(stylus({  
    use:[prefixer(), jeet()],  
    compress: true  
}))  
```

Now, after modularized gulp tasks with `gulp-load-plugins`, I've:

```css  
.pipe(plugins.stylus({  
    use:[prefixer(), jeet()],  
    compress: true  
}))  
```

But prefixer() and jeet() not working.  

```  
[14:17:09] Starting 'stylus'...  
[14:17:09] 'stylus' errored after 466 ms  
[14:17:09] ReferenceError: jeet is not defined  
    at Gulp.<anonymous> (/home/ednilson/Projects/web/workflow/workflow-stylus/tasks/stylus.js:6:22)  
    at module.exports (/home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/orchestrator/lib/runTask.js:34:7)  
    at Gulp.Orchestrator._runTask (/home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/orchestrator/index.js:273:3)  
    at Gulp.Orchestrator._runStep (/home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/orchestrator/index.js:214:10)  
    at Gulp.Orchestrator.start (/home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/orchestrator/index.js:134:8)  
    at /home/ednilson/Projects/web/workflow/workflow-stylus/tasks/watch.js:6:17  
    at write (/home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/gulp-watch/index.js:123:9)  
    at /home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/vinyl-file/index.js:52:4  
    at /home/ednilson/Projects/web/workflow/workflow-stylus/node_modules/graceful-fs/graceful-fs.js:78:16  
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)  
```

I tried with plugins.prefixer() and not working too.  

Also, I tried declare in `gulpfile.js`:  

```js  
plugins.prefixer = require('autoprefixer-stylus');  
plugins.jeet = require('jeet');  
```  

How can I fix this?  

Thanks everyone!!

**Comment by jackfranklin** [comment]
By default, this plugin only loads packages that start with `gulp-*` or `gulp.`.

You need to change the `pattern` option - see docs here: https://github.com/jackfranklin/gulp-load-plugins#options.

Can you let me know if that fixes it?

**Comment by ednilsonamaral** [comment]
Hi @jackfranklin, how are you?  

Thanks for your help!  

I solved this require `jeet()` in the stylus task, not in `gulpfile.js`. The code is here:  

```js  
module.exports = function (gulp, plugins, config) {  
    const jeet = require('jeet'),  
          rupture = require('rupture'),  
          nib = require('nib'),  
          prefixer = require('autoprefixer-stylus');  

    plugins.browserSync = require('browser-sync').create();  
    const reload = plugins.browserSync.reload;  

    gulp.task('stylus', function(){  
        gulp.src(config.stylusSrcFolder + '/main.styl')  
            .pipe(plugins.plumber())  
            .pipe(plugins.stylus({  
                use: [prefixer(), jeet(), nib(), rupture()],  
                compress: true  
            }))  
            .pipe(gulp.dest(config.stylusSrcFolder))  
            .pipe(plugins.rename('styles.css'))  
            .pipe(gulp.dest(config.stylusDestFolder))  
            .pipe(reload({stream: true}));  
    });  
};  
```
