### ISSUE TITLE
DEBUG not in IOptions

### ISSUE THREAD

**Issue by marmelin** [jackfranklin/gulp-load-plugins#129]
Added the DEBUG option to the gulp-load-plugins configuration and got the following error:

````
[09:49:44] Requiring external module ts-node/register

E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
**gulpfile.ts (8,5): Argument of type '{ DEBUG: boolean; pattern: string[]; scope: string[]; camelize: true; lazy: false; }' is not assignable to parameter of type 'IOptions'.**
  Object literal may only specify known properties, and 'DEBUG' does not exist in type 'IOptions'. (2345)
    at getOutput (E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:307:15)
    at E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:336:16
    at Object.compile (E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:496:11)
    at Module.m._compile (E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:392:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\app\GIT\v2-web-client\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
````
It is imported like this:

```
import * as glplugins from 'gulp-load-plugins';

const plugins = <any>glplugins({
    DEBUG: true,
    pattern: ['gulp-*','webpack*'],
    scope: ['dependencies', 'devDependencies', 'peerDependencies'], 
    camelize: true, 
    lazy: false, 
});
```
The IOptions type definition does not have a DEBUG option!:

```
declare module 'gulp-load-plugins' {
	interface IOptions {
		/** the glob(s) to search for, default ['gulp-*', 'gulp.*'] */
		pattern?: string[];
		/** where to find the plugins, searched up from process.cwd(), default 'package.json' */
		config?: string;
		/** which keys in the config to look within, default ['dependencies', 'devDependencies', 'peerDependencies'] */
		scope?: string[];
		/** what to remove from the name of the module when adding it to the context, default /^gulp(-|\.)/ */
		replaceString?: RegExp;
		/** if true, transforms hyphenated plugin names to camel case, default true */
		camelize?: boolean;
		/** whether the plugins should be lazy loaded on demand, default true */
		lazy?: boolean;
		/** a mapping of plugins to rename, the key being the NPM name of the package, and the value being an alias you define */
		rename?: IPluginNameMappings;
	}
```

Does the DEBUG option work if I add it to the type definition? 

```
OS: Windows 10
NPM: 5.3.0
NODE: 6.10.3

```

**Comment by jackfranklin** [comment]
Where is this type definition coming from? I didn't define it. It sounds like the definition is indeed out of date.

**Comment by jameelmoses** [comment]
Closing this due to inactivity and the TypeScript definition being outside of the scope of this plugin, although I'm happy to re-open if this is still an issue and with more information, notably a reply to @jackfranklin  on where the definition is coming from.
