### ISSUE TITLE
Error: Cannot fing module 'glob'

### ISSUE THREAD

**Issue by halleycarleton** [jackfranklin/gulp-load-plugins#54]
when running my gulpfile I get the error: `Error: Cannot find module 'glob'`. This seems to be triggered by gulp-load-plugins. This has only been a problem since moving over to a linux machine.

When I remove gulp-load-plugins from my gulpfile I don't get the error anymore.

Gulp v3.8.10
Node v0.10.25
Ubuntu 14.04

```
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/username/projects/my_project/node_modules/gulp-load-plugins/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by jackfranklin** [comment]
This is interesting...sounds like a dependency of something gulp-load-plugins needs isn't being installed properly from:

`
    at Object.<anonymous> (/home/username/projects/my_project/node_modules/gulp-load-plugins/node_modules/findup-sync/lib/findup-sync.js:15:12)
`

**Comment by halleycarleton** [comment]
After some further digging I think this is due to some permission issues with my node/npm install. I'll report back here after I get that figured to say if it fixed the issue.

**Comment by halleycarleton** [comment]
That seems to have been the issue. Now that I have my permissions all sorted out everything seems to be working. Sorry for the false alarm!
