### ISSUE TITLE
AssertionError: path must be a string

### ISSUE THREAD

**Issue by maxgrass** [jackfranklin/gulp-load-plugins#66]
```
[13:46:10] AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (C:\source\ECSWebApplications\CloudFramework\node_modules\gulp-load-plugins\index.js:37:14)
    at Object.defineProperty.get (C:\source\ECSWebApplications\CloudFramework\node_modules\gulp-load-plugins\index.js:59:18)
```

plugins:
gulp-if
gulp-change
gulp-filesinstream

normal notation `x = require('blabla')` works

It worked with v0.8.0, broken on v0.8.1

**Comment by maxgrass** [comment]
modifying 

$$: require('gulp-load-plugins')(
        {config: '../../package.json'}
    ),


to

$$: require('gulp-load-plugins')()

fixed the issue. Might be that very bug with wrong node_modules directory.
